define_text_styles!({
    large_title_regular => (Weight::NORMAL, 26.0),
    large_title_emphasized => (Weight::BOLD, 26.0),
    title_1_regular => (Weight::NORMAL, 22.0),
    title_1_emphasized => (Weight::BOLD, 22.0),
    title_2_regular => (Weight::NORMAL, 17.0),
    title_2_emphasized => (Weight::BOLD, 17.0),
    title_3_regular => (Weight::NORMAL, 17.0),
    title_3_emphasized => (Weight::SEMI_BOLD, 15.0),
    headline_regular => (Weight::BOLD, 13.0),
    headline_emphasized => (Weight::EXTRA_BOLD, 13.0),
    body_regular => (Weight::NORMAL, 13.0),
    body_emphasized => (Weight::SEMI_BOLD, 13.0),
    callout_regular => (Weight::NORMAL, 12.0),
    callout_emphasized => (Weight::SEMI_BOLD, 12.0),
    subheadline_regular => (Weight::NORMAL, 11.0),
    subheadline_emphasized => (Weight::SEMI_BOLD, 11.0),
    footnote_regular => (Weight::NORMAL, 10.0),
    footnote_emphasized => (Weight::SEMI_BOLD, 10.0),
    caption_1_regular => (Weight::NORMAL, 10.0),
    caption_1_emphasized => (Weight::MEDIUM, 10.0),
    caption_2_regular => (Weight::MEDIUM, 10.0),
    caption_2_emphasized => (Weight::SEMI_BOLD, 10.0)
});
